// <auto-generated />
using System;
using Infrastructure.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.CatalogDb
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260724022142_SqlServer_CatalogStatsFunction")]
    partial class SqlServer_CatalogStatsFunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Catalog.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("IntroVideoFileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("intro_video_file_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]")
                        .HasColumnName("tags");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("thumbnail_file_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedById", "DeletedAt", "CreatedAt");

                    b.ToTable("courses", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_courses_currency_iso3", "LEN(price_currency)=3 AND price_currency COLLATE Latin1_General_CS_AS LIKE '[a-z][a-z][a-z]'");

                            t.HasCheckConstraint("ck_courses_price_amount_nonneg", "price_amount >= 0");

                            t.HasCheckConstraint("ck_courses_title_len", "LEN(title) BETWEEN 3 AND 200");
                        });
                });

            modelBuilder.Entity("Domain.Catalog.CourseReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("course_reviews", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_reviews_rating", "rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Domain.Catalog.Course", b =>
                {
                    b.OwnsOne("Domain.Catalog.CourseTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("title");

                            b1.HasKey("CourseId");

                            b1.HasIndex("Value");

                            b1.ToTable("courses", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("Domain.Primatives.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("CourseId");

                            b1.ToTable("courses", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
