// <auto-generated />
using System;
using Infrastructure.Orders;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.OrdersDb
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<string>("CourseTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("course_title_snapshot");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("paid_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("stripe_payment_intent_id IS NOT NULL");

                    b.HasIndex("BuyerId", "CourseId")
                        .IsUnique();

                    b.HasIndex("BuyerId", "CreatedAt");

                    b.ToTable("orders", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_orders_currency_iso3", "LEN(price_currency)=3 AND price_currency COLLATE Latin1_General_CS_AS LIKE '[a-z][a-z][a-z]'");

                            t.HasCheckConstraint("ck_orders_price_amount_nonneg", "price_amount >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Orders.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("CoursesOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("courses_owner_id");

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset>("CurrentPeriodStart")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("current_period_start");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("stripe_subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasFilter("stripe_subscription_id IS NOT NULL");

                    b.HasIndex("BuyerId", "CoursesOwnerId");

                    b.ToTable("subscriptions", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_period", "current_period_end > current_period_start");
                        });
                });

            modelBuilder.Entity("Infrastructure.Orders.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("key");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("BuyerId", "Key")
                        .IsUnique();

                    b.ToTable("idempotency", "orders");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.OwnsOne("Shared.Kernel.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
